dotnet/BethanysPieShop/BethanysPieShop/Controllers/PieController.cs
using BethanysPieShop.Models;
using BethanysPieShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BethanysPieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;
        public PieController(ICategoryRepository categoryRepository, IPieRepository pieRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }
        public IActionResult List()
        {
            // ViewBag.CurrentCategory = "Cheese cakes";
            // return View(_pieRepository.AllPies);
            PieListViewModel pieListViewModel = new PieListViewModel
            (_pieRepository.AllPies, "All Pies");
            return View(pieListViewModel);
        }
        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();
            return View(pie);
        }
    }
}

dotnet/BethanysPieShop/BethanysPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Bethany's Pie Shop</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <link rel="stylesheet" href="~/lib/bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css">
    <script src='main.js'></script>
</head>

<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary"
                aria-label="Bethany's Pie Shop navigation header">
                <div class="container-xl">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <img src="~/images/bethanys-pie-shop-logo_horiz-white.png" width="151" height="47"
                            class="d-inline-block align-top mb-2 mt-1" alt="Bethany's Pie Shop Logo">
                    </a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Pie" asp-action="List" class="nav-link">Pies</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        @RenderBody()
    </div>
    <script src="~/lib/bootstrap/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js"
        integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
</body>

</html>